# Generated by Django 4.2.2 on 2023-06-20 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contents', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='archive',
            name='post_archive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contents.post', verbose_name='archive post'),
        ),
        migrations.AddField(
            model_name='archive',
            name='user_archive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.user', verbose_name='archive user'),
        ),
    ]
